apiVersion: v1
kind: Service
metadata:
  name: xdb-puppeteer-report
  namespace: logica-{{ .Values.env }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: public-port
      port: 80
      protocol: TCP
      targetPort: http-port